### ISSUE TITLE
MacOSX brew install iopt fails

### ISSUE THREAD

**Issue by lukavia** [udacity/CarND-MPC-Project#22]
When trying to install iopt on macosx sierra with brew I get: 
```
Warning: Calling 'depends_on :mpi' is deprecated!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/udacity/homebrew-carnd-mpc-project/mumps.rb:35:in `<class:Mumps>'
Please report this to the udacity/carnd-mpc-project tap!

Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/udacity/homebrew-carnd-mpc-project/mumps.rb:38:in `<class:Mumps>'
Please report this to the udacity/carnd-mpc-project tap!

==> Downloading http://mumps.enseeiht.fr/MUMPS_5.1.1.tar.gz
######################################################################## 100.0%
==> make alllib LIBEXT=.dylib AR= -dynamiclib -Wl,-install_name -Wl,/usr/local/Cellar/mumps/5.1.1_1/lib/$(notdir $@) -undefined dynamic_lookup -
Last 15 lines from /Users/lukav/Library/Logs/Homebrew/mumps/01.make:
clang -fPIC -I../include -O  -c symbfac.c -o symbfac.o
clang -fPIC -I../include -O  -c interface.c -o interface.o
clang -fPIC -I../include -O  -c sort.c -o sort.o
clang -fPIC -I../include -O  -c minpriority.c -o minpriority.o
dynamiclib -Wl,-install_name -Wl,/usr/local/Cellar/mumps/5.1.1_1/lib/libpord.dylib -undefined dynamic_lookup -o libpord.dylib graph.o gbipart.o gbisect.o ddcreate.o ddbisect.o nestdiss.o multisector.o gelim.o bucket.o tree.o symbfac.o interface.o sort.o minpriority.o
make[2]: dynamiclib: No such file or directory
make[2]: [libpord.dylib] Error 1 (ignored)
echo libpord.dylib
libpord.dylib
if [ "./PORD/lib/" != "" ] ; then \
	  cp ./PORD/lib//libpord.dylib lib/libpord.dylib; \
	fi;
cp: ./PORD/lib//libpord.dylib: No such file or directory
make[1]: *** [lib/libpord.dylib] Error 1
make: *** [c] Error 2

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
udacity/carnd-mpc-project

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:220:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:178:in `open_api'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:278:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:225:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:238:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:368:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:364:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:418:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
```

**Comment by lukavia** [comment]
Managed to install ipopt from another tap: 
```
brew tap dpo/openblas
brew install ipopt
```

**Comment by mvirgo** [comment]
Thanks for updating with your solution :) We'll look into whether that one works better (before it wasn't, but maybe they've since updated)
